#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Fri Apr 26 13:12:45 2040

@author: jstreffi-local

Input arguments:
	1 	Id of first experiment
	2	Id of second experiment
	3	Resulution of experiments
	4 	Parameter name in netcdf file
	5 	Parameter name in name of netcdf file
	6 	Basepath of experiments on this machine
	7	Number by which the variable should be diveded before plotting (e.g 9.81 for pressure)
	8 	Plotoutput path on this machine
	9	Name of colormap module
	10	List of colorbar points
"""
from __future__ import division
import sys
import random as rd
import numpy as np
import pandas as pd
from scipy import signal
from scipy.io import netcdf
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
from matplotlib.colors import LinearSegmentedColormap
from matplotlib.pylab import *
from netCDF4 import Dataset
from tqdm import tqdm
import dask
from dask.delayed import delayed
from dask.diagnostics import ProgressBar
from ttictoc import TicToc
t = TicToc() ## TicToc("name")

np.set_printoptions(threshold=sys.maxsize)

def resample(xyobs,n,m):
	xstar = []
	ystar = []
	for ni in range(n):
		r = rd.randrange(0, xyobs.shape[0])
		xstar.append(xyobs[r])
	for mi in range(m):
		r = rd.randrange(0, xyobs.shape[0])
		ystar.append(xyobs[r])
	xbarstar = np.mean(np.asarray(xstar),axis=0)
	ybarstar = np.mean(np.asarray(ystar),axis=0)
	t = xbarstar - ybarstar
	return t

def bootstrap(xyobs, data1, data2):
	tstarobs = np.asarray(data2 - data1)
	tstar = []
	ta = []
	pvalue = []
	n = xyobs.shape[0]//2
	m = xyobs.shape[0]//2
	B = 50

	for bi in tqdm(range(B)):
		t = dask.delayed(resample)(xyobs,n,m)
		ta.append(t)
	with ProgressBar():
		tstar = dask.compute(ta)
	tstar = np.squeeze(np.asarray(tstar), axis = 0)
	pvalue = np.empty((tstarobs.shape[0],tstarobs.shape[1]))
	for lat in tqdm(range(0,tstarobs.shape[0])):
		for lon in range(0,tstarobs.shape[1]):
			p1 = tstar[:,lat,lon][tstar[:,lat,lon] >= tstarobs[lat,lon]].shape[0]/B
			p2 = tstar[:,lat,lon][tstar[:,lat,lon] >= -tstarobs[lat,lon]].shape[0]/B
			pvalue[lat,lon] = min(p1,p2)
  	return pvalue



if __name__ == '__main__':
	exp1=str(sys.argv[1])
	exp2=str(sys.argv[2])
	basepath=str(sys.argv[6])
	outpath=str(sys.argv[8])
	reslist=map(str, sys.argv[3].split(','))
	itimes=0
	fig =  plt.figure(figsize=(9,6))

	print(reslist)
	for res in reslist:
		print('reading files for',res)
		if res == 'T1279':
			ensnumber = 100
		if res == 'T511':
			ensnumber = 100
		if res == 'T159':
			ensnumber = 100
		datapath3=basepath+res+'/Experiment_'+exp1+'/'
		datapath4=basepath+res+'/Experiment_'+exp2+'/'    
		data1=[]
		data2=[]
		data3=[]
		data4=[]

		for i in tqdm(range(ensnumber)):
			ncfile1 = datapath3+'E'+str(i+1).zfill(3)+'/outdata/oifs/forcing/T2M_forcing_glob.nc'
			ncfile2 = datapath4+'E'+str(i+1).zfill(3)+'/outdata/oifs/forcing/T2M_forcing_glob.nc'
			ncfile3 = datapath3+'E'+str(i+1).zfill(3)+'/outdata/oifs/forcing/NET_SURF_forcing_glob.nc'
			ncfile4 = datapath4+'E'+str(i+1).zfill(3)+'/outdata/oifs/forcing/NET_SURF_forcing_glob.nc'

			data1.append(Dataset(ncfile1).variables["T2M"][:])
			data2.append(Dataset(ncfile2).variables["T2M"][:])
			data3.append(Dataset(ncfile3).variables["SSR"][:])
			data4.append(Dataset(ncfile4).variables["SSR"][:])

		ncfile5 = '/p/project/chhb19/jstreffi/input/amip-forcing/sic_input4MIPs_SSTsAndSeaIce_PAMIP_pdSST_pdSIC_gn_plot2.nc'
		ncfile6 = '/p/project/chhb19/jstreffi/input/amip-forcing/sic_input4MIPs_SSTsAndSeaIce_PAMIP_pdSST_fuSIC_Arctic_gn_plot2.nc'


		data1m = np.mean(np.asarray(data1),axis=0)
		data2m = np.mean(np.asarray(data2),axis=0)
		data3m = np.mean(np.asarray(data3),axis=0)
		data4m = np.mean(np.asarray(data4),axis=0)
		data5m = Dataset(ncfile5).variables["sic"][:]
		data6m = Dataset(ncfile6).variables["sic"][:]

		# Calculating Bootstrap test
		xyobs12 = np.asarray(np.concatenate([data1,data2]))
		xyobs34 = np.asarray(np.concatenate([data3,data4]))
		t.tic()
		#pvalue12 = bootstrap(xyobs12, data1m, data2m)
		#pvalue34 = bootstrap(xyobs34, data3m, data4m)
		t.toc()
		print(t.elapsed)

		# Plotting

		fig, ax = plt.subplots()
		N = 12
		drange = pd.date_range("2000-06", periods=N, freq="MS")


		plotT2M,=ax.plot(drange,np.squeeze(data2m-data1m),linewidth=3,color='Blue')
		#plt.fill_between(drange,((,facecolor='Blue',alpha=0.1)
		ax.set_ylim(ymin=-0.5,ymax=5.5)

		ax2=ax.twinx()
                plotNET,=ax2.plot(drange,np.squeeze(data4m-data3m),linewidth=3,color='Red')
		ax2.set_ylim(ymin=-400000,ymax=150000)

		ax3=ax.twinx()
                plotNET,=ax3.plot(drange,np.squeeze(data6m-data5m),linewidth=3,color='Black')
		ax3.set_ylim(ymin=-0.25,ymax=0.05)
		

		ax.set_xticks(drange)
		fig.savefig(outpath+res+'_forcing.png', dpi=300)



